### ISSUE TITLE
2.4.0.beta.4 - Carthage

### ISSUE THREAD

**Issue by charlymr** [charlymr/XlsxReaderWriter#13]
For the moment, Carthage is not release for this version as I need to have the architecture for the new WatchOS in ZipArchive. It will be soon.

https://github.com/ZipArchive/ZipArchive/issues/474

**Comment by ddaddy** [comment]
I believe the zip archive has been updated. Can we get the Carthage release as a non beta?

**Comment by ddaddy** [comment]
Are you still following this project?
Can you please release the Carthage version as non beta?

**Comment by ddaddy** [comment]
Has the latest release been released for Carthage now?

**Comment by charlymr** [comment]
Nearly. Fixing it now should be done today

**Comment by charlymr** [comment]
Should work now

**Comment by ddaddy** [comment]
I am struggling with 1 issue since this last update. I usually commit my Carthage/Checkouts/ folder to git so I always have dependancies to hand if they ever disappear but for some reason I can not commit this. I keep getting an error about /Carthage/Checkouts/XlsxReaderWriter/Carthage/Checkouts/ZipArchive/... is beyond a symbolic link.
No matter what I try, I cannot commit this to git.

**Comment by ddaddy** [comment]
Never mind, I got it committed by completely removing it and starting again. Thx
