### ISSUE TITLE
Xcode 12 warnings - Double-quoted include

### ISSUE THREAD

**Issue by ddaddy** [charlymr/XlsxReaderWriter#23]
Since Xcode 12 enables `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES` this framework throws up lots of warnings as the `#import`'s  should use angled brackets instead of quotes.

<img width="1200" alt="Screenshot 2020-08-24 at 10 25 01" src="https://user-images.githubusercontent.com/1425808/91027652-47f15280-e5f4-11ea-9f63-dafaa94608d9.png">

**Comment by ddaddy** [comment]
I've spend 2 days trying to fix this issue but get twisted in circles because of the `Carthage` & `CocoaPods` integrations.
`SSZipArchive` builds as `SSZipArchive` when using CocoaPods, but `ZipArchive` when using Carthage which is making it very tricky to work on. The project seems to rely on both the CocoaPod and Carthage build of `SSZipArchive`

I noticed in the readme you mention that CocoaPods is broken. What are your thoughts on this going forward?
Can we remove all the CocoaPods stuff and just use Carthage? Or are you wanting to fix the CocoaPods implementation?

**Comment by charlymr** [comment]
Hello.

Actually the cocoapods breaking is due to the fact I don’t own the the cocoapods entry so I cannot update it there, hence the workaround.

We can use either cocoapods or Carthage. We may need to update the SSZipArchive dependencies given that they did update there side.

I will try and have a look this week.

Thanks,

Denis

**Comment by charlymr** [comment]
Sorry took me a while to update. It's updated now. Thanks again for your contribution
